name: Deploy Databricks Bundle

# ---- KHI NAO CHAY? ----
on:
  push:
    branches:
      - dev          
      - main         


jobs:

  # === DEPLOY DEV ===
  deploy-dev:
    name: "Deploy to DEV"
    if: github.ref == 'refs/heads/dev'       # Chi chay khi push len branch dev
    runs-on: ubuntu-latest
    steps:

      # Buoc 1: Lay code tu Git
      - name: Checkout code
        uses: actions/checkout@v4

      # Buoc 2: Cai Databricks CLI
      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      # Buoc 3: Deploy len DEV workspace
      # Token duoc luu trong GitHub Secrets (Settings > Secrets and variables > Actions)
      - name: Deploy to DEV
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
        run: |
          databricks bundle deploy -t dev

  # === DEPLOY PROD ===
  deploy-prod:
    name: "Deploy to PROD"
    if: github.ref == 'refs/heads/main'      # Chi chay khi merge vao main
    runs-on: ubuntu-latest
    steps:

      # Buoc 1: Lay code tu Git
      - name: Checkout code
        uses: actions/checkout@v4

      # Buoc 2: Cai Databricks CLI
      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      # Buoc 3: Deploy len PROD workspace
      - name: Deploy to PROD
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
        run: |
          databricks bundle deploy -t prod
