name: Deploy Databricks Bundle

# ---- KHI NAO CHAY? ----
on:
  push:
    branches:
      - dev
      - main


jobs:


  deploy-dev:
    name: "Deploy to DEV"
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy to DEV
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
        run: |
          cd DAB
          databricks bundle deploy -t dev

  # === DEPLOY PROD ===
  deploy-prod:
    name: "Deploy to PROD"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy to PROD
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
        run: |
          cd DAB
          databricks bundle deploy -t prod
